import { expect, test } from "@playwright/test";
import type { Page } from "@playwright/test";
import { importMedia, setMode } from "./helpers.js";

/**
 * Importing a camera raw file.
 *
 * The decoding is unit-tested against files built to the specification. What
 * only this can check is that a raw file dropped on the real app becomes a
 * clip: identified from its bytes, developed, registered, and drawn.
 *
 * The fixture is generated by `scripts/make_test_dng.mjs` and its contents are
 * known exactly — a ramp with a neutral square in the middle. That square is
 * what makes the check meaningful rather than "something appeared".
 */

const DNG = "photos/sensor-ramp-64x48.dng";

/** The colour at a fraction across the preview, as drawn. */
async function previewPixel(
  page: Page,
  fx: number,
  fy: number,
): Promise<number[]> {
  return page.evaluate(
    ([x, y]) => {
      const canvas = document.querySelector("#preview") as HTMLCanvasElement;
      const ctx = canvas.getContext("2d")!;
      const px = ctx.getImageData(
        Math.round(canvas.width * x!),
        Math.round(canvas.height * y!),
        1,
        1,
      ).data;
      return [px[0]!, px[1]!, px[2]!, px[3]!];
    },
    [fx, fy],
  );
}

test("a DNG imports and becomes a clip", async ({ page }) => {
  await importMedia(page, DNG);
  await setMode(page, "photo");
  await page.waitForTimeout(800);

  // It reached the bin and the timeline, which means it was identified,
  // developed and registered like any other image.
  await expect(page.locator(".media-item")).toHaveCount(1);
  expect(await page.locator(".clip").count()).toBeGreaterThan(0);
});

test("the developed picture is drawn, and its neutral square is neutral", async ({
  page,
}) => {
  // The load-bearing check. Grey in the middle means the CFA phase, the black
  // level, the demosaic and the colour matrix are all right: an error in any of
  // them tints it, and a tint is exactly what a user would notice and could not
  // explain.
  await importMedia(page, DNG);
  await setMode(page, "photo");
  await page.waitForTimeout(1200);

  const centre = await previewPixel(page, 0.5, 0.5);
  expect(centre[3]).toBe(255);
  // Neutral: the three channels within a few codes of each other.
  const spread = Math.max(...centre.slice(0, 3)) - Math.min(...centre.slice(0, 3));
  expect(spread).toBeLessThan(12);
  // And not black or blown — a decode that failed to a flat frame would also
  // be "neutral".
  expect(centre[0]).toBeGreaterThan(60);
  expect(centre[0]).toBeLessThan(240);
});

test("the picture has real content, not a flat field", async ({ page }) => {
  // The fixture ramps red down and blue up across the frame, so the two sides
  // must differ. Without this, a decoder that returned mid-grey everywhere
  // would pass the neutrality check perfectly.
  await importMedia(page, DNG);
  await setMode(page, "photo");
  await page.waitForTimeout(1200);

  const left = await previewPixel(page, 0.18, 0.5);
  const right = await previewPixel(page, 0.82, 0.5);

  // Red falls left to right and blue rises.
  expect(left[0]!).toBeGreaterThan(right[0]!);
  expect(right[2]!).toBeGreaterThan(left[2]!);
});

test("a raw format needing the extended decoder is refused in words", async ({
  page,
}) => {
  // LibRaw is not shipped, so a CR3 cannot be opened. What matters is that the
  // refusal names the camera and format and says the decoder is *not loaded* —
  // a problem with a cause — rather than "unsupported file".
  await page.goto("/", { waitUntil: "networkidle" });
  await page.waitForTimeout(400);

  await page.evaluate(() => {
    // A minimal Canon CR3: an ISO-BMFF ftyp box with the crx brand.
    const bytes = new Uint8Array(64);
    bytes.set(new TextEncoder().encode("\0\0\0\x18ftypcrx "), 0);
    const file = new File([bytes], "shot.cr3", {
      type: "application/octet-stream",
    });
    const input = document.getElementById("file-input") as HTMLInputElement;
    const transfer = new DataTransfer();
    transfer.items.add(file);
    input.files = transfer.files;
    input.dispatchEvent(new Event("change", { bubbles: true }));
  });

  const toast = page.locator("#toast");
  await expect(toast).toContainText("CR3", { timeout: 10_000 });
  await expect(toast).toContainText("not loaded");
  await expect(toast).toHaveClass(/error/);
  // Nothing was imported.
  await expect(page.locator(".media-item")).toHaveCount(0);
});

test("an ordinary image still imports untouched", async ({ page }) => {
  // Every JPEG passes through the raw path first. "Not raw" is the common case
  // and must be silent — a stray refusal here would break all importing.
  await importMedia(page, "photos/colour-chart-512x512.jpg");
  await setMode(page, "photo");
  await page.waitForTimeout(600);

  await expect(page.locator(".media-item")).toHaveCount(1);
  await expect(page.locator("#toast")).not.toHaveClass(/error/);
});
